---
version: "3"

volumes:
  sensu-backend-data: {}

services:
  sensu-backend:
    image: sensu/sensu:latest
    container_name: sensu-backend
    ports:
    #  Web UI
    - 3000:3000
    # API
    - 8080:8080
    # Websocket
    - 8081:8081
    volumes:
    - "./backend.yml:/etc/sensu/backend.yml"
    - "sensu-backend-data:/var/lib/sensu/etcd"
    environment:
      - SENSU_BACKEND_CLUSTER_ADMIN_USERNAME=admin
      - SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD=Password123
    command: "sensu-backend start --log-level info"

